from selenium import webdriver

driver = webdriver.Chrome()

# Navigate to url
driver.get("http://www.example.com")

# Adds the cookie into current browser context
driver.add_cookie({"sp_id.cf1a":"0f0ec199-0fff-481b-b929-5a3c475cc680.1613647522.42.1614464729.1614442098.d2387646-4042-48b0-8ad0-1dcbcb73a7a2",
                    "Created":"Thu, 18 Feb 2021 11:25:21 GMT",
                    "Domain":".tradingview.com",
                    "Expires / Max-Age":"Mon, 27 Feb 2023 22:25:29 GMT",
                    "HostOnly":"false",
                    "HttpOnly":"false",
                    "Last Accessed":"Sat, 27 Feb 2021 22:25:29 GMT",
                    "Path":"/",
                    "SameSite":"None",
                    "Secure":"true",
                    "Size":"120",
                   })
driver.add_cookie({"_sp_ses.cf1a":"*",
                    "Created":"Sat, 27 Feb 2021 22:25:28 GMT",
                    "Domain":".tradingview.com",
                    "Expires / Max-Age":"Sat, 27 Feb 2021 22:55:29 GMT",
                    "HostOnly":"false",
                    "HttpOnly":"false",
                    "Last Accessed":"Sat, 27 Feb 2021 22:25:29 GMT",
                    "Path":"/",
                    "SameSite":"None",
                    "Secure":"true",
                    "Size":"13",
                   })
driver.add_cookie({"cachec":"ee4e24a2-b581-47b4-adc7-71832f1584b1",
                    "Created":"Sat, 27 Feb 2021 22:25:28 GMT",
                    "Domain":".tradingview.com",
                    "Expires / Max-Age":"Tue, 31 Dec 2030 00:00:00 GMT",
                    "HostOnly":"false",
                    "HttpOnly":"false",
                    "Last Accessed":"Sat, 27 Feb 2021 22:25:29 GMT",
                    "Path":"/",
                    "SameSite":"None",
                    "Secure":"true",
                    "Size":"42",
                   })
driver.add_cookie({"etg":"ee4e24a2-b581-47b4-adc7-71832f1584b1",
                    "Created":"Sat, 27 Feb 2021 22:25:28 GMT",
                    "Domain":".tradingview.com",
                    "Expires / Max-Age":"Session",
                    "HostOnly":"false",
                    "HttpOnly":"false",
                    "Last Accessed":"Sat, 27 Feb 2021 22:25:29 GMT",
                    "Path":"/",
                    "SameSite":"None",
                    "Secure":"true",
                    "Size":"39",
                   })
driver.add_cookie({"png":"ee4e24a2-b581-47b4-adc7-71832f1584b1",
                    "Created":"Sat, 27 Feb 2021 22:25:28 GMT",
                    "Domain":".tradingview.com",
                    "Expires / Max-Age":"Session",
                    "HostOnly":"false",
                    "HttpOnly":"false",
                    "Last Accessed":"Sat, 27 Feb 2021 22:25:29 GMT",
                    "Path":"/",
                    "SameSite":"None",
                    "Secure":"true",
                    "Size":"39",
                   })
driver.add_cookie({"sessionid":"z1h46dnrpg4f1ofyyi5u8cpm3703ppp8",
                    "Created":"Sat, 27 Feb 2021 22:25:28 GMT",
                    "Domain":".tradingview.com",
                    "Expires / Max-Age":"Mon, 31 May 2021 13:54:44 GMT",
                    "HostOnly":"false",
                    "HttpOnly":"true",
                    "Last Accessed":"Sat, 27 Feb 2021 22:25:29 GMT",
                    "Path":"/",
                    "SameSite":"lax",
                    "Secure":"true",
                    "Size":"41",
                   })
driver.add_cookie({"tv_ecuid":"ee4e24a2-b581-47b4-adc7-71832f1584b1",
                    "Created":"Sat, 27 Feb 2021 22:25:28 GMT",
                    "Domain":".tradingview.com",
                    "Expires / Max-Age":"Tue, 31 Dec 2030 00:00:00 GMT",
                    "HostOnly":"false",
                    "HttpOnly":"false",
                    "Last Accessed":"Sat, 27 Feb 2021 22:25:29 GMT",
                    "Path":"/",
                    "SameSite":"none",
                    "Secure":"false",
                    "Size":"44",
                   })
driver.add_cookie({"will_start_trial":"1",
                    "Created":"Sat, 27 Feb 2021 22:25:28 GMT",
                    "Domain":".tradingview.com",
                    "Expires / Max-Age":"Session",
                    "HostOnly":"false",
                    "HttpOnly":"false",
                    "Last Accessed":"Sat, 27 Feb 2021 22:25:29 GMT",
                    "Path":"/",
                    "SameSite":"none",
                    "Secure":"false",
                    "Size":"17",
                   })
driver.add_cookie({"{2a61aa71-1cfe-4661-b1c3-67ce9b0c1915}":"value",
                    "Created":"Sat, 27 Feb 2021 22:25:28 GMT",
                    "Domain":".tradingview.com",
                    "Expires / Max-Age":"Sun, 28 Feb 2021 14:41:02 GMT",
                    "HostOnly":"false",
                    "HttpOnly":"false",
                    "Last Accessed":"Sat, 27 Feb 2021 22:25:29 GMT",
                    "Path":"/",
                    "SameSite":"none",
                    "Secure":"false",
                    "Size":"43",
                   })